<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/assets/css/jkit.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/font-awesome.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/bootstrap-responsive.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/app.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/assets/js/jquery.js')
            ->prependFile($this->basePath() . 'assets/js/bootstrap.js')
            ->prependFile($this->basePath() . '/assets/js/jquery.jkit.1.1.10.js')
            ->prependFile($this->basePath() . '/assets/js/jquery.easing.1.3.js')
        ; ?>

        <script type="text/javascript">
            $("[data-rel=tooltip]").tooltip();
        </script>

        <script type="text/javascript">
            $(document).ready(function () {
                $('body').jKit();
            });
        </script>
    </head>
    <body>
    <?php //echo $this->content; ?>
        <div id="header">
            <div class="navbar navbar-static-top">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </a>
                        <a href="index.php.htm"> <h1>.</h1></a>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Header -->

        <div class="container">
            <!-- Start Info Unit -->
            <div id="info-unit"> <div class="alert alert-block alert-info fade in">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <h4 class="alert-heading">Ajude-nos a melhorar nossa cidade.</h4>
                    <p>Envie Videos,Fotos.</p>
                </div>
            </div>
            <!-- End Info Unit -->
            <div class="row-fluid" >
                <?php echo $this->content; ?>

                <!-- INICIO BARRA LATERAL -->
                <div id="side-section" class="span3">
                    <ul class="nav nav-list">
                        <li class="nav-header">filter by</li>
                        <li class="active"><a href="#"><i class="icon-time"></i> Adicionados Recentemente</a></li>
                        <li><a href="#"><i class="icon-heart-empty"></i> Mais visitados</a></li>
                        <li><a href="#"><i class="icon-star-empty"></i> ---</a></li>
                    </ul>

                    <div class="module-top"><i class="icon-lock"></i> Login</div>
                    <div class="module">
                        <form method="post" action="?" data-jkit="[form:validateonly=true]">
                            <fieldset>
                                <label class="label-main">Usuário</label>
                                <input name="miniusername" class="span10" id="miniusername"  type="text" data-jkit="[validate:required=true;min=3;max=10;error=Please enter your username (3-10 characters)]">
                                <label class="label-main">Senha</label>
                                <input name="miniusername" class="span10" id="miniusername"  type="text" data-jkit="[validate:required=true;min=3;max=10;error=Please enter your username (3-10 characters)]">
                                <p><label class="checkbox"><input type="checkbox">remember me</label></p>
                                <button name="send" type="submit" value="Submit"  class="btn btn-small">Entrar</button>
                            </fieldset>
                        </form></div>

                    <div class="module-top"><i class="icon-comments"></i>Últimos comentários</div>
                    <div class="module">
                        <ul class="comment-list">
                            <li class="comment">         
                                <div class="comment-body">
                                    <h4 class="comment-heading">titulo <span class="time">4:34am</span></h4>
                                    <p>comentario</p>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
                </div>
                <!-- FIM DA BARRA LATERAL -->
            </div>

            <footer class="footer">
                <div class="container">
                    <div class="row-fluid">
                        <div class="span6"> <p class="copyright"><img class="foot-logo" src="assets/img/logo-ts.png" alt="Brand Logo"/> &copy; 2013 <strong>Watchopolis</strong> Video Portal Theme - Crafted by <a href="https://wrapbootstrap.com/user/themestrap">Themestrap</a> </p></div>
                        <div class="span6">   <div class="pagination pull-right">
                                <ul>
                                    <li><a data-rel="tooltip" data-placement="top" data-original-title="Follow us on Twitter" href="#"><i class="icon-twitter"></i></a></li>
                                    <li><a data-rel="tooltip" data-placement="top" data-original-title="Share us on Pinterest" href="#"><i class="icon-pinterest"></i></a></li>
                                    <li><a data-rel="tooltip" data-placement="top" data-original-title="Like us on Facebook" href="#"><i class="icon-facebook"></i></a></li>
                                    <li><a data-rel="tooltip" data-placement="top" data-original-title="+1 us on Google+" href="#"><i class="icon-google-plus"></i></a></li>          
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
    </body>
