<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/assets/css/jkit.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/font-awesome.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/bootstrap-responsive.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/app.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/assets/js/jquery.js')
            ->prependFile($this->basePath() . 'assets/js/bootstrap.js')
            ->prependFile($this->basePath() . '/assets/js/jquery.jkit.1.1.10.js')
            ->prependFile($this->basePath() . '/assets/js/jquery.easing.1.3.js')
        ; ?>

        <script type="text/javascript">
            $("[data-rel=tooltip]").tooltip();
        </script>

        <script type="text/javascript">
            $(document).ready(function () {
                $('body').jKit();
            });
        </script>


    </head>
    <body>
    <?php //echo $this->content; ?>
        <div id="header">
            <div class="navbar navbar-static-top">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </a>
                        <a href="index.php.htm"> <h1>.</h1></a>
                        <div class="nav-collapse collapse">
                            <form class="navbar-form pull-left">
                                <div class="input-append">
                                    <input class="span3" id="appendedInputButtons" type="text">
                                    <button class="btn btn-primary" type="button"><i class="icon-search"></i></button>
                                </div>           
                            </form>
                            <ul class="nav">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Features <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="404.htm">404 Page</a></li>
                                        <li><a href="page-elements.htm">Page elements</a></li>
                                        <li><a href="login.htm">Login Page</a></li>
                                        <li><a href="register.htm">Register Page</a></li>
                                        <li><a href="pricing-plans.htm">Pricing Plans</a></li>
                                    </ul>
                                </li>
                            </ul>
                            <p class="navbar-text pull-right">
                                <a href="login.htm" class="btn btn-primary">Login</a>   <a href="register.htm"   class="btn btn-default">Registre-se</a>
                            </p> 
                        </div><!--/.nav-collapse -->
                    </div>
                </div>
            </div>
        </div>

        <!-- End Header -->



        <div class="container">

            <!-- Start Info Unit -->

            <div id="info-unit"> <div class="alert alert-block alert-info fade in">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <h4 class="alert-heading">Ajude-nos a melhorar nossa cidade.</h4>
                    <p>Envie Videos,Fotos.</p>
                </div>
            </div>

            <!-- End Info Unit -->


            <div>



                <div class="row-fluid" >
                    <div class="span9 main-section">


                        <!-- Options bar (Left Section) -->

                        <div class="options-bar"><select class="span2 pull-left"><option>Ordenar </option>
                                <option>Data</option>
                                <option>Popular</option>
                                <option>Mais comentados</option>
                            </select>
                            <span><strong>1</strong> Reclamações</span>
                        </div>

                        <!-- End Options Bar -->


                        <!-- Start Left Section -->

                        <div class="row-fluid">
                            <ul class="thumbnails">
                                <?php for($i = 0 ; $i < 5 ; $i++): ?>
                                <li class="span3">
                                    <div class="thumbnail">
                                        <img data-src="holder.js/300x200" alt="300x200"  src="http://tnaudiencia.pn5.com.br/wp-content/uploads/2014/05/Datena.jpg">
                                        <div class="caption">
                                            <h6><a href="">Título</a></h6>
                                            <p><small>Mensagem</small></p>
                                            <p><i class="icon-user"></i> <small><b>Raphael Iarussi</b></small>  </p>
                                            <p><i class="icon-calendar"></i> <small><b>10/10/2014 10:30</b></small>  </p>
                                            
                                        </div>
                                    </div>
                                </li>
                                <?php endfor; ?>
                            </ul>
                        </div>

                        <div class="pagination pagination-small pull-right">
                            <ul>
                                <li><a href="#">«</a></li>
                                <li><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                                <li><a href="#">4</a></li>
                                <li><a href="#">5</a></li>
                                <li><a href="#">»</a></li>
                            </ul>
                        </div>


                    </div>

                </div>
            </div>


            <footer class="footer">
                <div class="container">
                    <div class="row-fluid">
                        <div class="span6"> <p class="copyright"><img class="foot-logo" src="assets/img/logo-ts.png" alt="Brand Logo"/> &copy; 2013 <strong>Watchopolis</strong> Video Portal Theme - Crafted by <a href="https://wrapbootstrap.com/user/themestrap">Themestrap</a> </p></div>
                        <div class="span6">   <div class="pagination pull-right">
                                <ul>
                                    <li><a data-rel="tooltip" data-placement="top" data-original-title="Follow us on Twitter" href="#"><i class="icon-twitter"></i></a></li>
                                    <li><a data-rel="tooltip" data-placement="top" data-original-title="Share us on Pinterest" href="#"><i class="icon-pinterest"></i></a></li>
                                    <li><a data-rel="tooltip" data-placement="top" data-original-title="Like us on Facebook" href="#"><i class="icon-facebook"></i></a></li>
                                    <li><a data-rel="tooltip" data-placement="top" data-original-title="+1 us on Google+" href="#"><i class="icon-google-plus"></i></a></li>          
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
    </body>
