<div class="row-fluid" >
    <div class="span9 main-section">


        <!-- Options bar (Left Section) -->

        <div class="options-bar"><select class="span2 pull-left"><option>Ordenar </option>
                <option>Data</option>
                <option>Popular</option>
                <option>Mais comentados</option>
            </select>
            <span><strong>1</strong> Reclamações</span>
        </div>

        <!-- End Options Bar -->


        <!-- Start Left Section -->

        <div class="row-fluid">
            <ul class="thumbnails">
                <?php for($i = 0 ; $i < 5 ; $i++): ?>
                <li class="span3">
                    <div class="thumbnail">
                        <img data-src="holder.js/300x200" alt="300x200"  src="http://portaldoamazonas.com/wp-content/uploads/2016/04/prod.jpg">
                        <div class="caption">
                            <h6><a href="">Título</a></h6>
                            <p><small>Mensagem</small></p>
                            <p><i class="icon-user"></i> <small><b>Raphael Iarussi</b></small>  </p>
                            <p><i class="icon-calendar"></i> <small><b>10/10/2014 10:30</b></small>  </p>
                            
                        </div>
                    </div>
                </li>
                <?php endfor; ?>
            </ul>
        </div>

        <div class="pagination pagination-small pull-right">
            <ul>
                <li><a href="#">«</a></li>
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">»</a></li>
            </ul>
        </div>
    </div>
</div>